add_newline = false

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
vicmd_symbol = "[⇷](bold green)"

[git_status]
conflicted_count.enabled = true
stashed_count.enabled = true
modified_count.enabled = true
staged_count.enabled = true 

[aws]
disabled = true

[package]
disabled = true
