add_newline = false

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
vicmd_symbol = "[⇷](bold green)"

[git_status]
conflicted.enabled = true
stashed.enabled = true
modified.enabled = true
staged.enabled = true 

[aws]
disabled = true

[package]
disabled = true

[status]
symbol = ""
disabled = false

#[kubernetes]
#disabled=false

