#!/usr/bin/env python3
import pyperclip
from http.server import HTTPServer, BaseHTTPRequestHandler


s = pyperclip.paste()
hostName = "0.0.0.0"
serverPort = 8000
class SimpleHTTPRequestHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.end_headers()
        self.wfile.write(bytes(s,"utf-8"))


if __name__ == "__main__":        
    webServer = HTTPServer((hostName, serverPort), SimpleHTTPRequestHandler)
    print("Server started http://%s:%s" % (hostName, serverPort))

    try:
        webServer.serve_forever()
    except KeyboardInterrupt:
        pass

    webServer.server_close()
    print("Server stopped.")

